import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  carte: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginHorizontal: 15,
    marginBottom: 20,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  titreCarte: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 10,
  },
  contenuCarte: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  conteneurMetrique: {
    width: '30%',
    marginBottom: 15,
    position: 'relative',
  },
  metrique: {
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  texteMetrique: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 5,
  },
  infobulle: {
    position: 'absolute',
    backgroundColor: '#333',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: 'center',
    zIndex: 10,
  },
  texteInfobulle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  flecheInfobulle: {
    position: 'absolute',
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#333',
    alignSelf: 'center',
  },
  piedCarte: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  textePied: {
    fontSize: 12,
    color: '#666',
  },
  boutonModifier: {
    backgroundColor: '#007bff',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  texteBoutonModifier: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  boutonAjouterNote: {
    backgroundColor: '#007bff',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  texteBoutonAjouterNote: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  iconContainer: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  conteneurSignal: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  signalWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  texteSignal: {
    fontSize: 14,
    fontWeight: '500',
  },
  qualificationSignal: {
    fontSize: 14,
    fontStyle: 'italic',
    marginLeft: 5,
  },
});