import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  fondModal: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  conteneurModal: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    width: '100%',
    maxHeight: '90%',
  },
  boutonFermer: {
    alignSelf: 'flex-end',
    padding: 5,
  },
  titreModal: {
    fontSize: 22,
    fontWeight: '700',
    color: '#333',
    marginBottom: 15,
    textAlign: 'center',
  },
  conteneurEtablissement: {
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 15,
  },
  etiquette: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  texteEtablissement: {
    fontSize: 16,
    color: '#555',
  },
  sousTitreSection: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginTop: 15,
    marginBottom: 10,
  },
  etiquetteSaisie: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginBottom: 8,
  },
  champSaisie: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#333',
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
  },
  sectionNotifications: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 15,
    padding: 10,
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
  },
  boutonNotification: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  texteNotification: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  scrollViewJours: {
    maxHeight: 200,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 8,
    paddingHorizontal: 5,
  },
  ligneJour: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  jourHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  etiquetteJour: {
    fontSize: 16,
    color: '#333',
    marginLeft: 10,
    fontWeight: '500',
  },
  jourContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  jourSwitch: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  switchJour: {
    marginLeft: 10,
  },
  boutonPlageHoraire: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f8ff',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  textePlageHoraire: {
    fontSize: 14,
    color: '#0a7ea4',
  },
  boutonsModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  boutonAnnuler: {
    backgroundColor: '#ff4d4d',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flex: 0.48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  boutonSauvegarder: {
    backgroundColor: '#007bff',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flex: 0.48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  texteBouton: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
    boutonPlagesHoraires: {
    backgroundColor: '#0a7ea4',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    marginVertical: 15,
  },
  texteBoutonPlages: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
    boutonValider: {
    backgroundColor: '#4CAF50',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
  },
  texteBoutonValider: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
    ligneJourFullscreen: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: '#fff',
  },
  jourContainerFullscreen: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  jourSwitchFullscreen: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  jourHeaderFullscreen: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  etiquetteJourFullscreen: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
  boutonPlageHoraireFullscreen: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f8ff',
    padding: 10,
    borderRadius: 8,
  },
  textePlageHoraireFullscreen: {
    color: '#0a7ea4',
    fontSize: 13,
    fontWeight: '500',
  },
timeDisplayContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#f0f8ff',
  padding: 10,
  borderRadius: 8,
  justifyContent: 'center',
  minWidth: 140,
},
});