import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  fondModal: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  conteneurModal: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  boutonFermer: {
    position: 'absolute',
    top: 15,
    right: 15,
    zIndex: 10,
  },
  titreModal: {
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
  },
  conteneurCapteur: {
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
    padding: 10,
    borderRadius: 8,
  },
  etiquette: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  texteCapteur: {
    fontSize: 16,
    color: '#555',
    fontWeight: '500',
  },
  sousTitreSection: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginTop: 15,
    marginBottom: 10,
  },
  champSaisie: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#333',
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
    textAlignVertical: 'top',
  },
  boutonsModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  boutonAnnuler: {
    backgroundColor: '#ff4d4d',
    paddingVertical: 12, 
    paddingHorizontal: 8,
    borderRadius: 8,
    flex: 0.48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  boutonSauvegarder: {
    backgroundColor: '#007bff',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
    flex: 0.48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  texteBouton: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  noteExistante: {
    backgroundColor: '#f0f8ff',
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#007bff',
  },
  dateNote: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
    fontWeight: '500',
  },
  texteNote: {
    fontSize: 14,
    color: '#333',
  },
  aucuneNote: {
    textAlign: 'center',
    color: '#666',
    fontStyle: 'italic',
    marginVertical: 20,
  },
  noteHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  deleteButton: {
    padding: 3,
  },
datePickerContainer: {
  marginVertical: 10,
  width: '100%',
},
dateLabel: {
  fontSize: 16,
  fontWeight: '500',
  marginBottom: 5,
  color: '#333',
},
dateTimeSelectors: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  width: '100%',
},
datePickerButton: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#f0f0f0',
  padding: 10,
  borderRadius: 8,
  borderWidth: 1,
  borderColor: '#ddd',
  flex: 3,
  marginRight: 8,
},
timePickerButton: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#f0f0f0',
  padding: 10,
  borderRadius: 8,
  borderWidth: 1,
  borderColor: '#ddd',
  flex: 2,
},
dateText: {
  fontSize: 16,
  color: '#333',
  marginRight: 5,
},
boutonNotesExistantes: {
  backgroundColor: '#0a7ea4',
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  padding: 12,
  borderRadius: 8,
  marginVertical: 15,
},
texteBoutonNotes: {
  color: 'white',
  fontWeight: '600',
  fontSize: 16,
},
boutonValider: {
  backgroundColor: '#4CAF50',
  paddingVertical: 14,
  paddingHorizontal: 20,
  borderRadius: 8,
  alignItems: 'center',
  justifyContent: 'center',
  marginTop: 15,
},
texteBoutonValider: {
  color: '#fff',
  fontSize: 16,
  fontWeight: '600',
},
});